const HISTORY_STATUSES = [2, 3, 4, 5, 6, 7, 8];

const STATUSES_FOR_CHANGE = [1, 3, 4, 5, 6, 7];

const STATUSES_NOT_ROLLBACK = [1];

export { HISTORY_STATUSES, STATUSES_FOR_CHANGE, STATUSES_NOT_ROLLBACK };
