const PRE_BOOKING_SHIPMENT = 1;
const ACTIVE_BOOKING_SHIPMENT = 2;
const DELIVERED_SHIPMENT = 3;
const CANCELED_SHIPMENT = 4;

export { PRE_BOOKING_SHIPMENT, ACTIVE_BOOKING_SHIPMENT, DELIVERED_SHIPMENT, CANCELED_SHIPMENT };
